/* Test was generated by Claude based on project definition and my existing code */

#include <stdio.h>
#include <string.h>
#include "stg_proto.h"

/* Verified PHYSICAL frame from spec section 4. */
static const uint8_t good[] = {
    0xA5,0x5A,0x21,0x00,0x02,0x1F,0x01,0x08,0x4E,0xE5,0x93,0x18,0x00,0x00,0x00,0x00,
    0x10,0x02,0xCE,0x09,0x11,0x02,0xBA,0x09,0x12,0x02,0xB5,0x05,0x13,0x02,0xA9,0x05,
    0x14,0x02,0x04,0x00,0x15,0x01,0x00,0xC3,0x12
};

static int check(const char *name, int ok)
{
    printf("%-28s %s\n", name, ok ? "pass" : "FAIL");
    return ok ? 0 : 1;
}

/* Frame fields match the spec. */
static int frame_ok(const stg_frame *fr)
{
    return fr->type == 0x02 && fr->seq == 0x1F && fr->len == 33;
}

static int test_crc(void)
{
    uint16_t c = stg_crc16((const uint8_t *)"123456789", 9);
    return check("crc check vector", c == 0x29B1);
}

static int test_one_shot(void)
{
    stg_framer f;
    stg_frame  fr;
    stg_framer_init(&f);
    stg_framer_feed(&f, good, sizeof good);

    int got = stg_framer_next(&f, &fr);
    return check("whole frame at once", got == 1 && frame_ok(&fr));
}

static int test_byte_at_a_time(void)
{
    stg_framer f;
    stg_frame  fr;
    int frames = 0;

    stg_framer_init(&f);
    for (size_t i = 0; i < sizeof good; i++) {
        stg_framer_feed(&f, &good[i], 1);
        while (stg_framer_next(&f, &fr) == 1) {
            if (frame_ok(&fr)) frames++;
        }
    }
    return check("one byte at a time", frames == 1);
}

static int test_two_frames(void)
{
    stg_framer f;
    stg_frame  fr;
    int frames = 0;

    stg_framer_init(&f);
    stg_framer_feed(&f, good, sizeof good);
    stg_framer_feed(&f, good, sizeof good);

    while (stg_framer_next(&f, &fr) == 1) {
        if (frame_ok(&fr)) frames++;
    }
    return check("two frames back to back", frames == 2);
}

static int test_garbage_prefix(void)
{
    stg_framer f;
    stg_frame  fr;
    /* A lone 0xA5 not followed by 0x5A, and a stray 0x5A. */
    const uint8_t junk[] = { 0x00, 0xA5, 0x11, 0x5A, 0xFF };

    stg_framer_init(&f);
    stg_framer_feed(&f, junk, sizeof junk);
    stg_framer_feed(&f, good, sizeof good);

    int got = stg_framer_next(&f, &fr);
    return check("garbage before sync", got == 1 && frame_ok(&fr));
}

static int test_bad_crc(void)
{
    stg_framer f;
    stg_frame  fr;
    uint8_t    bad[sizeof good];

    memcpy(bad, good, sizeof good);
    bad[10] ^= 0xFF;   /* corrupt a payload byte */

    stg_framer_init(&f);
    stg_framer_feed(&f, bad, sizeof bad);

    int got = stg_framer_next(&f, &fr);
    return check("corrupt crc rejected", got == 0);
}

static int test_truncated_then_good(void)
{
    stg_framer f;
    stg_frame  fr;
    int frames = 0;

    stg_framer_init(&f);
    stg_framer_feed(&f, good, 20);              /* partial */
    stg_framer_feed(&f, good, sizeof good);     /* complete */

    while (stg_framer_next(&f, &fr) == 1) {
        if (frame_ok(&fr)) frames++;
    }
    return check("truncated then good", frames == 1);
}

int main(void)
{
    int fails = 0;
    fails += test_crc();
    fails += test_one_shot();
    fails += test_byte_at_a_time();
    fails += test_two_frames();
    fails += test_garbage_prefix();
    fails += test_bad_crc();
    fails += test_truncated_then_good();

    printf("\n%d failure(s)\n", fails);
    return fails != 0;
}